version: "3"
services:
   adguardhome:
     image: adguard/adguardhome:v0.107.44
     container_name: adguardhome
     restart: unless-stopped
     ports:
       # plain DNS.
       - 53:53/tcp
       - 53:53/udp
       # add if you intend to use AdGuard Home as a DHCP server.
       # - 67:67/udp
       # - 68:68/udp
       # - 68:68/tcp
       #  add if you are going to use AdGuard Home's admin panel as well as run AdGuard Home as an HTTPS/DNS-over-HTTPS server.
       - 8080:80/tcp
       - 443:443/tcp
       - 443:443/udp
       - 3000:3000/tcp
       # add if you are going to run AdGuard Home as a DNS-over-QUIC server.
       - 853:853/udp
       # add if you are going to run AdGuard Home as a DNS-over-TLS server.
       - 853:853/tcp
       # add if you are going to run AdGuard Home as a DNSCrypt server.
       - 5443:5443/tcp
       # debugging profiles.
       - 5443:5443/udp
       - 6060:6060/tcp
     volumes:
       - ./work:/opt/adguardhome/work
       - ./conf:/opt/adguardhome/conf
